// <auto-generated />
namespace Quartalsarbeit_GR1.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Telefonnummer : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Telefonnummer));
        
        string IMigrationMetadata.Id
        {
            get { return "202106042215371_Telefonnummer"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
